# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_CPP_MIN_LOG_LEVEL: 3  # tell XLA to be quiet

strategy:
  matrix:
    Python37_cpu:
      python.version: '3.7'
      JAX_PLATFORM_NAME: cpu
    Python38_cpu:
      python.version: '3.8'
      JAX_PLATFORM_NAME: cpu
    Python36_cpu:
      python.version: '3.9'
      JAX_PLATFORM_NAME: cpu    # Python36_gpu:
    # Python37_gpu:
    #   python.version: '3.7'
    #   JAX_PLATFORM_NAME: gpu
    #   XLA_PYTHON_CLIENT_MEM_FRACTION: 0.1  # don't use all of GPU memory
    # Python38_gpu:
    #   python.version: '3.8'
    #   JAX_PLATFORM_NAME: gpu
    #   XLA_PYTHON_CLIENT_MEM_FRACTION: 0.1  # don't use all of GPU memory
    #   python.version: '3.9'
    #   JAX_PLATFORM_NAME: gpu
    #   XLA_PYTHON_CLIENT_MEM_FRACTION: 0.1  # don't use all of GPU memory
    
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    sudo apt install -y swig
    python -m pip install --upgrade pip wheel
    pip install -r requirements.txt
    pip install -r requirements.dev.txt
    pip install pytest-azurepipelines
  displayName: 'Install requirements'

- script: python -m flake8 coax
  displayName: 'Run flake8'

- script: python -m pytest --cov=coax --cov-report=xml --cov-report=html coax -v
  displayName: 'Run pytest'

- script: |
    sudo apt install -y pandoc
    pip install -r requirements.doc.txt
    python setup.py build_sphinx
  displayName: 'Build docs'
